### ISSUE TITLE
Code published in Circuit Cellar is not published here.

### ISSUE THREAD

**Issue by cjheath** [fabiopjve/ULWOS#1]
Reading Circuit Cellar issue 218 (January 2017) which references this Git repository,
I note that neither example here contains the INT_IT function shown there.

I wanted to report an issue over that function, which idles when the selected task
is in Delay mode, even if a different task is currently runnable. Is that intended?

**Comment by fabiopjve** [comment]
Hello Clifford,

I am gonna look at it and get back to you as soon as possible ok?

I wrote that code almost a year ago and I am not sure if the published code
matches what is in my github account!

But as far as I remember, a delay should not select another task even if it
is ready to run. At first I designed the task switcher that way, so an idle
task can force the CPU in low power mode during its time slot, without
impacting on other running tasks. Is that what you wanted to know?

But I will take a look at my github repo and get back to you asap.

ULWOS was mostly an exercise to learn more about the inner of a task
switcher and multitasking principles. But I guess it can be customized to
do some pretty cool tasks! Please, feel free to make any considerations
about it!

Thank you very much!

Fábio Pereira

Em 17 de jan de 2017 22:54, "Clifford Heath" <notifications@github.com>
escreveu:

Reading Circuit Cellar issue 218 (January 2017) which references this Git
repository,
I note that neither example here contains the INT_IT function shown there.

I wanted to report an issue over that function, which idles when the
selected task
is in Delay mode, even if a different task is currently runnable. Is that
intended?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/fabiopjve/ULWOS/issues/1>, or mute the thread

**Comment by cjheath** [comment]
"a delay should not select another task even if it is ready to run" is a perfectly valid design decision if you want fixed timing (RTOS), but it should be an explicit decision, and that wasn't obvious in your article.

Also, there are better ways of handling the delay timers than looping through (decrementing remaining time) all tasks on every tick.

Anyhow, thanks for your article, and for publishing your code (even though I won't use it myself).

**Comment by fabiopjve** [comment]
Hello again Mr. Clifford,

You are completely right! The code published in Circuit Cellar issue 318 was not posted here. Thank you for pointing that out. I just uploaded the project files!

Regarding the behaviour of idle tasks, I agree with you, that design decision wasn't shown in text. I believe I had so much to write and forgot to cover some of these design decisions. There was so much to say and so less space to write!

Thank you again for taking time to report the issues!

**Comment by cjheath** [comment]
Thanks for publishing the code!
